services:
  postgres:
    image: postgres:15-alpine
    container_name: pacagen_hub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pacagen
      POSTGRES_PASSWORD: pacagen_dev_pass
      POSTGRES_DB: pacagen_hub_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pacagen']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
