import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const MOCK_WEBHOOK_DATA = {
  id: 6801619878202,
  admin_graphql_api_id: "gid://shopify/Order/6801619878202",
  app_id: 580111,
  browser_ip: "2600:100f:a00b:b33b:8442:b8a3:deea:b3d6",
  buyer_accepts_marketing: true,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "hWN3T1tXYKJO7s42qzrxlgQy",
  checkout_id: 40287726108986,
  checkout_token: "4fc49b1f3d137951d5bd889af795ea79",
  client_details: {
    accept_language: "en-US",
    browser_height: null,
    browser_ip: "2600:100f:a00b:b33b:8442:b8a3:deea:b3d6",
    browser_width: null,
    session_hash: null,
    user_agent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1",
  },
  closed_at: null,
  company: null,
  confirmation_number: "URIAWZG8K",
  confirmed: true,
  contact_email: "joiesims@gmail.com",
  created_at: "2025-10-19T21:15:30-04:00",
  currency: "USD",
  current_shipping_price_set: {
    shop_money: { amount: "11.29", currency_code: "USD" },
    presentment_money: { amount: "11.29", currency_code: "USD" },
  },
  current_subtotal_price: "39.44",
  current_subtotal_price_set: {
    shop_money: { amount: "39.44", currency_code: "USD" },
    presentment_money: { amount: "39.44", currency_code: "USD" },
  },
  current_total_additional_fees_set: null,
  current_total_discounts: "18.56",
  current_total_discounts_set: {
    shop_money: { amount: "18.56", currency_code: "USD" },
    presentment_money: { amount: "18.56", currency_code: "USD" },
  },
  current_total_duties_set: null,
  current_total_price: "50.73",
  current_total_price_set: {
    shop_money: { amount: "50.73", currency_code: "USD" },
    presentment_money: { amount: "50.73", currency_code: "USD" },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  customer_locale: "en-US",
  device_id: null,
  discount_codes: [{ code: "AL246FZPEB", amount: "6.96", type: "percentage" }],
  duties_included: false,
  email: "joiesims@gmail.com",
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: null,
  landing_site:
    "/cart/c/hWN3T1tXYKJO7s42qzrxlgQy?key=f293eeb5b4881f4f9627e1d025a1ff1d",
  landing_site_ref: null,
  location_id: null,
  merchant_business_entity_id: "MTgxNDgzNjk0Mzk0",
  merchant_of_record_app_id: null,
  name: "#88940",
  note: "_igId : ig_180019edf4a234a945829bc50dfbf563fd51\n_igTestGroups : 1160b90e9bad\n_floatab : 1\n\n",
  note_attributes: [
    {
      name: "_tnsid",
      value:
        "local-445011c220d323daf18b65c9f7b1aa8aa520f302ef872bf000339827c9b03319",
    },
    { name: "igId", value: "ig_180019edf4a234a945829bc50dfbf563fd51" },
    { name: "pacagen_hub_ab_user_id", value: "test-user-123" },
    { name: "pacagen_hub_ab_variant_id", value: "1a9e8ab4-fb4d-4274-88e6-1fab1d476e15" },
    { name: "pacagen_hub_ab_experiment_id", value: "6a4b5407-38de-4541-85c5-1fe75f72818f" },
  ],
  number: 87940,
  order_number: 88940,
  order_status_url:
    "https://checkout.pacagen.com/81483694394/orders/06c580f0743c63421a4588edc16e4d34/authenticate?key=0c3d1c24df4198bb9509d6cff64270f6",
  original_total_additional_fees_set: null,
  original_total_duties_set: null,
  payment_gateway_names: ["shopify_payments"],
  phone: "+13607700585",
  po_number: null,
  presentment_currency: "USD",
  processed_at: "2025-10-19T21:15:27-04:00",
  reference: null,
  referring_site: "https://shop.app/",
  source_identifier: null,
  source_name: "web",
  source_url: null,
  subtotal_price: "39.44",
  subtotal_price_set: {
    shop_money: { amount: "39.44", currency_code: "USD" },
    presentment_money: { amount: "39.44", currency_code: "USD" },
  },
  tags: "Alia, JG, Subscription First Order",
  tax_exempt: false,
  tax_lines: [],
  taxes_included: false,
  test: false,
  token: "06c580f0743c63421a4588edc16e4d34",
  total_cash_rounding_payment_adjustment_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  total_cash_rounding_refund_adjustment_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  total_discounts: "18.56",
  total_discounts_set: {
    shop_money: { amount: "18.56", currency_code: "USD" },
    presentment_money: { amount: "18.56", currency_code: "USD" },
  },
  total_line_items_price: "58.00",
  total_line_items_price_set: {
    shop_money: { amount: "58.00", currency_code: "USD" },
    presentment_money: { amount: "58.00", currency_code: "USD" },
  },
  total_outstanding: "0.00",
  total_price: "50.73",
  total_price_set: {
    shop_money: { amount: "50.73", currency_code: "USD" },
    presentment_money: { amount: "50.73", currency_code: "USD" },
  },
  total_shipping_price_set: {
    shop_money: { amount: "11.29", currency_code: "USD" },
    presentment_money: { amount: "11.29", currency_code: "USD" },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  total_tip_received: "0.00",
  total_weight: 703,
  updated_at: "2025-10-19T21:45:43-04:00",
  user_id: null,
  billing_address: {
    first_name: "David",
    address1: "12402 217th St E",
    phone: "+13607700585",
    city: "Graham",
    zip: "98338",
    province: "Washington",
    country: "United States",
    last_name: "Gloudeman",
    address2: null,
    company: null,
    latitude: 47.0583397,
    longitude: -122.2650457,
    name: "David Gloudeman",
    country_code: "US",
    province_code: "WA",
  },
  customer: {
    id: 9500408480058,
    created_at: "2025-10-19T21:12:21-04:00",
    updated_at: "2025-10-19T21:45:45-04:00",
    first_name: "Joie",
    last_name: "C Gloudeman",
    state: "enabled",
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    email: "joiesims@gmail.com",
    phone: "+13607700585",
    currency: "USD",
    tax_exemptions: [],
    admin_graphql_api_id: "gid://shopify/Customer/9500408480058",
    default_address: {
      id: 11076573069626,
      customer_id: 9500408480058,
      first_name: "Joie",
      last_name: "Gloudeman",
      company: null,
      address1: "12402 217th street E.",
      address2: null,
      city: "Graham",
      province: "Washington",
      country: "United States",
      zip: "98338",
      phone: "+13607700585",
      name: "Joie Gloudeman",
      province_code: "WA",
      country_code: "US",
      country_name: "United States",
      default: true,
    },
  },
  discount_applications: [
    {
      target_type: "line_item",
      type: "automatic",
      value: "20.0",
      value_type: "percentage",
      allocation_method: "each",
      target_selection: "entitled",
      title: "SUBSCRIPTION",
    },
    {
      target_type: "line_item",
      type: "discount_code",
      value: "15.0",
      value_type: "percentage",
      allocation_method: "across",
      target_selection: "all",
      code: "AL246FZPEB",
    },
  ],
  fulfillments: [],
  line_items: [
    {
      id: 16501530263866,
      admin_graphql_api_id: "gid://shopify/LineItem/16501530263866",
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 544,
      name: "Cat Allergen Neutralizing Spray - Starter Pack / Floral Breeze",
      pre_tax_price: "39.44",
      pre_tax_price_set: {
        shop_money: { amount: "39.44", currency_code: "USD" },
        presentment_money: { amount: "39.44", currency_code: "USD" },
      },
      price: "58.00",
      price_set: {
        shop_money: { amount: "58.00", currency_code: "USD" },
        presentment_money: { amount: "58.00", currency_code: "USD" },
      },
      product_exists: true,
      product_id: 9895289913658,
      properties: [
        { name: "_igId", value: "ig_180019edf4a234a945829bc50dfbf563fd51" },
        { name: "_igTestGroups", value: "1160b90e9bad" },
        { name: "_floatab", value: "1" },
      ],
      quantity: 1,
      requires_shipping: true,
      sales_line_item_group_id: null,
      sku: "CANSSP",
      taxable: true,
      title: "Cat Allergen Neutralizing Spray",
      total_discount: "11.60",
      total_discount_set: {
        shop_money: { amount: "11.60", currency_code: "USD" },
        presentment_money: { amount: "11.60", currency_code: "USD" },
      },
      variant_id: 51235719708986,
      variant_inventory_management: "shopify",
      variant_title: "Starter Pack / Floral Breeze",
      vendor: "Pacagen",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          rate: 0.0,
          title: "Washington State Tax",
        },
      ],
      duties: [],
      discount_allocations: [
        {
          amount: "11.60",
          amount_set: {
            shop_money: { amount: "11.60", currency_code: "USD" },
            presentment_money: { amount: "11.60", currency_code: "USD" },
          },
          discount_application_index: 0,
        },
        {
          amount: "6.96",
          amount_set: {
            shop_money: { amount: "6.96", currency_code: "USD" },
            presentment_money: { amount: "6.96", currency_code: "USD" },
          },
          discount_application_index: 1,
        },
      ],
    },
    {
      id: 16501530755386,
      admin_graphql_api_id: "gid://shopify/LineItem/16501530755386",
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 159,
      name: "Lint Roller - Enrollment Gift",
      pre_tax_price: "0.00",
      pre_tax_price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      product_exists: true,
      product_id: 9837112426810,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sales_line_item_group_id: null,
      sku: "LR05",
      taxable: false,
      title: "Lint Roller - Enrollment Gift",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      variant_id: 50937117737274,
      variant_inventory_management: "shopify",
      variant_title: null,
      vendor: "Pacagen",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          rate: 0.0,
          title: "Washington State Tax",
        },
      ],
      duties: [],
      discount_allocations: [
        {
          amount: "0.00",
          amount_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          discount_application_index: 1,
        },
      ],
    },
    {
      id: 16501530886458,
      admin_graphql_api_id: "gid://shopify/LineItem/16501530886458",
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Welcome To Pacagen!",
      pre_tax_price: "0.00",
      pre_tax_price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      product_exists: true,
      product_id: 9837132316986,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sales_line_item_group_id: null,
      sku: "INSERT-2",
      taxable: false,
      title: "Welcome To Pacagen!",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      variant_id: 50937475694906,
      variant_inventory_management: "shopify",
      variant_title: null,
      vendor: "Pacagen",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          rate: 0.0,
          title: "Washington State Tax",
        },
      ],
      duties: [],
      discount_allocations: [
        {
          amount: "0.00",
          amount_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          discount_application_index: 1,
        },
      ],
    },
  ],
  payment_terms: null,
  refunds: [],
  shipping_address: {
    first_name: "Joie",
    address1: "12402 217th street E.",
    phone: "+13607700585",
    city: "Graham",
    zip: "98338",
    province: "Washington",
    country: "United States",
    last_name: "Gloudeman",
    address2: null,
    company: null,
    latitude: 47.0583397,
    longitude: -122.2650457,
    name: "Joie Gloudeman",
    country_code: "US",
    province_code: "WA",
  },
  shipping_lines: [
    {
      id: 5304825053498,
      carrier_identifier: null,
      code: "5 Day Shipping (3-5 Business Days)",
      current_discounted_price_set: {
        shop_money: { amount: "11.29", currency_code: "USD" },
        presentment_money: { amount: "11.29", currency_code: "USD" },
      },
      discounted_price: "11.29",
      discounted_price_set: {
        shop_money: { amount: "11.29", currency_code: "USD" },
        presentment_money: { amount: "11.29", currency_code: "USD" },
      },
      is_removed: false,
      phone: null,
      price: "11.29",
      price_set: {
        shop_money: { amount: "11.29", currency_code: "USD" },
        presentment_money: { amount: "11.29", currency_code: "USD" },
      },
      requested_fulfillment_service_id: null,
      source: "shopify",
      title: "5 Day Shipping (3-5 Business Days)",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          rate: 0.0,
          title: "Washington State Tax",
        },
      ],
      discount_allocations: [],
    },
    {
      id: 5304825086266,
      carrier_identifier: null,
      code: "5 Day Shipping (3-5 Business Days)",
      current_discounted_price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      discounted_price: "0.00",
      discounted_price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      is_removed: false,
      phone: null,
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "USD" },
        presentment_money: { amount: "0.00", currency_code: "USD" },
      },
      requested_fulfillment_service_id: null,
      source: "shopify",
      title: "5 Day Shipping (3-5 Business Days)",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "USD" },
            presentment_money: { amount: "0.00", currency_code: "USD" },
          },
          rate: 0.0,
          title: "Washington State Tax",
        },
      ],
      discount_allocations: [],
    },
  ],
  returns: [],
  line_item_groups: [],
};
